### PR TITLE
[Fix] (sentry-416): use Sentry v6 version

### PR DESCRIPTION
**Pull request by thinhvo0108**
* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
Bug fix

* **What is the current behavior?** (You can also link to an open issue here)
See #416 

* **What is the new behavior (if this is a feature change)?**
Use Sentry's v6.1.0 (from v6, the `hub.startSession` is used)

### CODE REVIEW

**Comment by thinhvo0108** [comment]
Got inspired from @namoscato (https://github.com/filestack/filestack-js/pull/417)

**Review by namoscato — COMMENTED** [review]
I'm guessing `package-lock.json` needs to be updated – perhaps by running:

```bash
npm i @sentry/minimal@^6.1.0
```

**Comment by namoscato** [comment]
@thinhvo0108 – FYI I pushed up another commit to https://github.com/filestack/filestack-js/pull/417 that also bumps this version. It might be best to try and consolidate all of this in one PR.

**Comment by thinhvo0108** [comment]
Cool, thanks @namoscato we can just use 1 fix, your fix (I mean)

I didn't include the `package-lock.json` as our local node/npm version may affect the changes, so I will include after confirming what current npm version is being used by our Filestack folks at the moment!

**Comment by namoscato** [comment]
> I didn't include the `package-lock.json` as our local node/npm version may affect the changes

I think this will just affect the version of `@sentry/minimal` installed with `filestack-js`.

**Pull request merged**
